apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: my-app
    type: frontend
spec:
  containers:
    - name: new-image
      image: aniket2525/new-repo:latest
      ports:
        - containerPort: 80